### ISSUE TITLE
Conflict with Mason nvim 

### ISSUE THREAD

**Issue by anoopd** [linux-cultist/venv-selector.nvim#122] opened 2024-05-17 09:58 UTC
I tried the plugin but it is conflicting with Mason .

**Comment by linux-cultist** [comment] 2024-05-17 10:03
Ok, do you have any details of what is happening or what you are doing?

**Comment by anoopd** [comment] 2024-05-18 00:11
Sorry for missing the details  ........... i was using the `regexp` version as i was a new user .  The error i was getting was  `failed to run config for mason.nvim` , and on my config file line 12 `loop or previous error loading module mason-lspconfig `  .

12th line is 
`local mason-lspconfig = require('mason-lspconfig')`

**Comment by linux-cultist** [comment] 2024-05-18 05:47
But there is no mention of this plugin in the error message? It's interesting, since the plugin has no interaction with Mason at all. It doesn't have it as a dependency even.

When do you get the error? When you open Mason?

**Comment by anoopd** [comment] 2024-05-18 06:35
Nope   .......... when i open nvim after installing this plugin  .......... if i remove this then there is no problem .  Have you ever tried it with mason installed  ?

**Comment by linux-cultist** [comment] 2024-05-18 06:46
I will try it on Lazyvim today, see if I get any conflicts. Hope I do so I can understand what's happening.

**Comment by linux-cultist** [comment] 2024-05-18 07:05
Are you using your own config or some neovim distribution?

**Comment by linux-cultist** [comment] 2024-05-18 07:17
I cant reproduce any issues in Lazyvim either. Here is a pic of mason and the plugin from lazyvim. The plugin is installed just like it says in the readme for the regexp branch (not using my local development version):

![image](https://github.com/linux-cultist/venv-selector.nvim/assets/126409588/cebb0760-f1ec-46dc-bbde-af32ea462bd2)

And here same thing with nvchad:

![image](https://github.com/linux-cultist/venv-selector.nvim/assets/126409588/47077955-e4d9-4fdb-a9d1-4d5e819b86ac)

**Comment by anoopd** [comment] 2024-05-18 11:25
Thank you   .......... I am running my own config and using mason-tool-installer ,maybe  that would be causing the error .

**Comment by linux-cultist** [comment] 2024-05-18 12:25
It could yeah. I used to have my own config for neovim for years but there was always these cases of something not working properly. So I switched to using a neovim distribution. But I wouldnt trade away the experience I got from having my own config. Learned very much about how things actually work.

But then I close this issue for now and I hope you find the reason. :)

**Closed by linux-cultist** 2024-05-18 12:25 UTC
Labels: regexp version

**Comment by anoopd** [comment] 2024-05-19 00:46
Hi, Just wanted to let you know that i was able to get it working by avoiding the "dependencies" part completely .   :)

**Comment by linux-cultist** [comment] 2024-05-19 04:56
Ok :) I hope you like it!
