### ISSUE TITLE
Automate with cwd

### ISSUE THREAD

**Issue by BonaBeavis** [linux-cultist/venv-selector.nvim#19] opened 2023-04-24 15:53 UTC
When the current working dir changes, would be a good time to retirve the venv from cache.

**Comment by linux-cultist** [comment] 2023-04-25 06:22
You mean you would want the plugin to check for a cached venv every time you change your cwd?

There would be a lot of unnecessary checks I think, since people use vim for a lot more than just python projects. But we could maybe add it as an option you can set.

It's also possible to write your own autocommand to execute VenvSelectCached on every cwd change, as a solution for now.

**Comment by igorlfs** [comment] 2023-04-29 19:19
I'm having a similar issue. My workflow consists of 
1. Launching neovim from home directory
2. Restoring a session in another directory with [persisted](https://github.com/olimorris/persisted.nvim)
3. Using a hook to activate the venv for the current project, i.e.,
```lua
au({ "User" }, {
    desc = "Venv autoselect",
    pattern = { "PersistedLoadPost", "PersistedTelescopeLoadPost" },
    group = ag("PersistedHooks", {}),
    callback = function()
        local venv = vim.fn.findfile("pyproject.toml", vim.fn.getcwd() .. ";")
        if venv ~= "" then
            require("venv-selector").retrieve_from_cache()
        end
    end,
})
```

The problem is that venv-select isn't aware of cwd changes, so it always thinks I'm in the home directory.

> You mean you would want the plugin to check for a cached venv every time you change your cwd?

I think we could make venv-select session aware by having an option to control how often that happens. Something along the lines of 
```lua
update_with_cwd = "never"    -- current behavior
               or "once"     -- update only once to update when loading a session, for instance
               or "always"   -- always updates cached venv (mention that it can be performance intensive?)
```

**Comment by igorlfs** [comment] 2023-05-01 13:51
The latest update fixes my use case, thanks linux-cultist! By the way, nice nickname!

**Comment by linux-cultist** [comment] 2023-05-03 16:13
I'm closing this but feel free to reopen if it's still an issue.

**Closed by linux-cultist** 2023-05-03 16:13 UTC

**Comment by igorlfs** [comment] 2023-05-03 16:35
Hey, actually, I'm having an issue that I need to restart the LSP to trigger it "hooking" to the selected venv. It is otherwise active, but due to some race condition, I need to use `:LspRestart` to make Pyright recognize the venv. It looks like when I open a session, and it loads some files, the LSP immediately attaches to these files (or at least does so at the same time the venv is being activated). Could `require("venv-selector").retrieve_from_cache()` check if LSP is active and if so, trigger a restart?
